name = "madgrades-dle"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "STATS_KV"
id = "2c0e93d6284f4e6fa682154907ce9da1"
